apiVersion: apps/v1
kind: Deployment
metadata:
  name: volunteer-matchmaking-back
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: volunteer-matchmaking-back
  template:
    spec:
      containers:
        - name: volunteer-matchmaking-back
          image: fake-image
          resources:
            requests:
              memory: 128Mi
              cpu: 0.1
            limits:
              memory: 256Mi
              cpu: 0.5
          ports:
            - containerPort: 80
              name: http
          envFrom:
          - configMapRef:
              name: volunteer-matchmaking-back-config
          # Uncomment the secretRef block below if your Playground application has secrets
          # See the README for instructions on how to create secrets
          - secretRef:
             name: volunteer-matchmaking-back-secrets
          readinessProbe:
            httpGet:
              port: http
              path: /
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
